baseURL = 'http://skhelmbrecht.github.io'
languageCode = 'en-us'
title = 'Sarah Helmbrecht'
theme = ['ananke', 'hugo-shortcode-gallery']
resourceDir = "../resources"

googleAnalytics = 'G-ZDFRFHQGY8'
enableRobotsTXT = true
disqusShortname = "skhelmbrecht-github-io"
enableEmoji = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[menus]
    [[menus.main]]
        name = 'About'
        pageRef = '/about'
        weight = 5
    [[menus.main]]
        name = 'Resume'
        pageRef = '/resume'
        weight = 10
    [[menus.main]]
        name = 'Projects'
        pageRef = '/projects'
        weight = 20
    [[menus.main]]
        name = 'Teaching'
        pageRef = '/teaching'
        weight = 30
    [[menus.main]]
        name = 'Blog'
        pageRef = '/blog'
        weight = 50

[params]
  text_color = "black"
  description = "An academic portfolio and blog."
  background_color_class = "custom-army-green"
  recent_posts_number = 3
  read_more_copy = "Read More"
  body_classes = "bg-white"
  post_content_classes = "bg-white"
  custom_css = ["academic/teaching.css", "academic/resources-page.css", "academic/resume.css", "academic/about.css"]

  [params.meta]
    favicon = true
