baseURL = 'http://skhelmbrecht.github.io'
languageCode = 'en-us'
title = 'SARAH HELMBRECHT'
theme = 'ananke'
resourceDir = "../resources"

googleAnalytics = ''
enableRobotsTXT = true
disqusShortname = "skhelmbrecht-github-io"
enableEmoji = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = "black"
  author = "Sarah Helmbrecht"
  description = "An academic portfolio and blog."
  background_color_class = "bg-black"
  recent_posts_number = 3
  read_more_copy = "Read More"
  body_classes = "bg-white"
  post_content_classes = "bg-white"
  custom_css = ["index.css", "tutoring.css", "teaching.css", "resources-page.css"]

  [params.meta]
    favicon = true
