baseURL = 'http://skhelmbrecht.github.io'
languageCode = 'en-us'
title = 'Sarah Helmbrecht'
theme = ['ananke', 'hugo-shortcode-gallery']
resourceDir = "../resources"

googleAnalytics = 'G-ZDFRFHQGY8'
enableRobotsTXT = true
disqusShortname = "skhelmbrecht-github-io"
enableEmoji = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[menus]
  [[menus.main]]
      name = 'Tutoring'
      pageRef = '/tutoring'
      weight = 10
  [[menus.main]]
      name = 'Academic'
      pageRef = '/academic'
      weight = 20
  [[menus.main]]
      name = 'Raymond'
      pageRef = '/raymond'
      weight = 30

  [[menus.tutoring]]
      name = 'Home'
      pageRef = '/tutoring'
      weight = 10
  [[menus.tutoring]]
      name = 'About'
      pageRef = '/tutoring/about'
      weight = 20
  [[menus.tutoring]]
      name = 'Services'
      pageRef = '/tutoring/services'
      weight = 30
  [[menus.tutoring]]
      name = 'Blog'
      pageRef = '/blog'
      weight = 40
  [[menus.tutoring]]
      name = 'Contact'
      pageRef = '/tutoring/contact'
      weight = 50

  [[menus.academic]]
      name = 'Home'
      pageRef = '/academic'
      weight = 10
  [[menus.academic]]
      name = 'Teaching'
      pageRef = '/academic/teaching'
      weight = 20
  [[menus.academic]]
      name = 'Projects'
      pageRef = '/projects'
      weight = 30
  [[menus.academic]]
      name = 'Resume'
      pageRef = '/academic/resume'
      weight = 40

[params]
  text_color = "black"
  description = "An academic portfolio and blog."
  background_color_class = "custom-army-green"
  recent_posts_number = 3
  read_more_copy = "Read More"
  body_classes = "bg-white"
  post_content_classes = "bg-white"
  custom_css = ["tutoring/index.css", "academic/teaching.css", "academic/resources-page.css", "academic/resume.css", "raymond.css", "tutoring/contact.css", "tutoring/about.css", "tutoring/services.css", "academic/index.css"]

  [params.meta]
    favicon = true
